print("nombre completo del estudiante a camelCase es nombCompleEstud")
print("numero de matricula a snake_case es numero_de_matricula")
print("total de ventas del mes a PascalCase es TotalDeVentas")
print("Limite maximo de intentos  SCREAMING_SNAKE_CASE es LIMITE_MAXIMO_INTENTOS")
print("Cantidad de productos a camelCase es cantidadProductos")