print("edad del usuario = edadUsuario")
print("El precio total del carrito de compras = PRECIO_TOTAL_COMPRAS")
print("El estado de inicio de sesion = estado_sesion")
print("El nombre del curso actual = NombCurso")
print("La temperatura promedio registrada = TEMP_ACTUAL_REGISTR")